use_frameworks!

platform :ios, '8.0'

target 'SVGAPlayerHippyModule_Example' do
  pod 'SVGAPlayerHippyModule', :path => '../'

  target 'SVGAPlayerHippyModule_Tests' do
    inherit! :search_paths

    
  end
end
